# ******************************Configuration for Ruff**************************
[tool.ruff]
exclude = [
  ".git",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
  "__pypackages__",
]

line-length = 100
target-version = "py310"
indent-width = 4

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`) codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F", "I"]
ignore = [
    "E203",
    "E501",
    "E722",
    "E741",
    "F821",
]

[tool.ruff.lint.isort]
# Force single line imports
force-single-line = false
# Split on trailing comma
split-on-trailing-comma = true

# ******************************Configuration for Pytest************************
[tool.pytest.ini_options]
filterwarnings = [
    "ignore::UserWarning:gymnasium.wrappers.rendering",
]
# 600s should be quite enough for a single test
# If your test exceeds this time, first check if there is inappropriate sleep
# or infinite loop.
# If your function do require a long time to run, please overide this by
# adding "@pytest.mark.timeout(300)" to your test.
# https://pypi.org/project/pytest-timeout/
timeout = 600

# ******************************Configuration for mypy**************************
[tool.mypy]
# Specify the files and directories to be checked ** please keep sorted **
files = [
    "./common",
    "./hands_on",
    "./practice",
]
namespace_packages = true
follow_imports = "silent"
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
disallow_any_generics = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_return_any = true
strict_optional = true

# list external modules with no typing below ** please keep sorted **
[[tool.mypy.overrides]]
module = "gymnasium.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "imageio.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "matplotlib.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "numpy.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pickle5.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pytest.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tqdm.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "torchvision.*"
ignore_missing_imports = true
